# Model: weights/NanoAgent-135M-think-v2
models:
  - model: HuggingFaceTB/SmolLM2-135M-Instruct
    parameters:
      weight: 0.2
  - model: weights/NanoAgent-135M-core
    parameters:
      weight: 0.4
  - model: weights/NanoAgent-135M-v13/final_checkpoint
    parameters:
      weight: 0.4

merge_method: linear
dtype: bfloat16